---
title: Hybrid Execution
subtitle: Combine pre-rendered and client-side WebAssembly computation
format: live-html
engine: knitr
toc: true
webr:
  packages: dplyr
---

{{< include ../_extensions/live/_knitr.qmd >}}

Transferring data through OJS variables allows for communication between the different execution contexts provided by the `quarto-live` extension.

## Build-time OJS data source

In standard Quarto code cell blocks data can be evaluated at build-time and exported as an [OJS data source](https://quarto.org/docs/interactive/ojs/data-sources.html). The data is then subsequently available to OJS blocks at runtime.

#### Source

````{.markdown filename="hybrid.qmd"}
```{{r}}
library(ggplot2)
glimpse(diamonds)
ojs_define(diamonds)
```

```{ojs}
diamonds
```
````

#### Output

```{r}
library(ggplot2)
head(diamonds)
ojs_define(diamonds)
```

```{ojs}
diamonds
```

### WebAssembly `quarto-live` cells

Since the build-time data export is available as an OJS variable, it can be imported back into an R or Python environment using the `input` code cell option.

With this, you can do further processing of data, in a serverless fasion, using client-side WebAssembly engines.

````{.markdown filename="hybrid.qmd"}
```{{webr}}
#| input:
#|   - diamonds
si1 <- diamonds |> dplyr::filter(clarity == "SI1")
plot(si1$depth, si1$price)
head(si1)
```
````

```{webr}
#| input:
#|   - diamonds
si1 <- diamonds |> dplyr::filter(clarity == "SI1")
plot(si1$depth, si1$price)
head(si1)
```

## Passing data between engines

The mechanism described in the previous section can also be used to pass data between WebAssembly engines.

#### Source

````markdown
```{{webr}}
#| edit: false
#| define:
#|   - mpg
# Process and export data from R
mpg <- mtcars |>
  dplyr::select(mpg, hp) |>
  dplyr::filter(mpg < 25)
```

```{{pyodide}}
#| edit: false
#| input:
#|   - mpg
# Import and plot data in Python

import matplotlib.pyplot as plt
import pandas as pd

df = pd.DataFrame(mpg)
plt.plot(df['mpg'], df['hp'])
plt.show()
```
````

#### Output

```{webr}
#| edit: false
#| define:
#|   - mpg
# Process and export data from R
mpg <- mtcars |>
  dplyr::select(mpg, hp) |>
  dplyr::filter(mpg < 25)
```

```{pyodide}
#| edit: false
#| input:
#|   - mpg
# Import and plot data in Python

import matplotlib.pyplot as plt
import pandas as pd

df = pd.DataFrame(mpg)
plt.plot(df['mpg'], df['hp'], 'o')
plt.show()
```
